"""sync_schema_with_models_persistent

Revision ID: 7bf669982e55
Revises: 9a9fc4631380
Create Date: 2026-03-27 13:23:56.895435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf669982e55'
down_revision: Union[str, Sequence[str], None] = '9a9fc4631380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'published_at')
    # ### end Alembic commands ###
