"""Add failed_component and root_cause to issues

Revision ID: 9a9fc4631380
Revises: a468225e15a8
Create Date: 2026-03-26 07:05:05.489556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9fc4631380'
down_revision: Union[str, Sequence[str], None] = 'a468225e15a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('failed_component', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('root_cause', sa.String(), nullable=True))
    op.create_index(op.f('ix_issues_failed_component'), 'issues', ['failed_component'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_failed_component'), table_name='issues')
    op.drop_column('issues', 'root_cause')
    op.drop_column('issues', 'failed_component')
    # ### end Alembic commands ###
