"""add unique constraint to title

Revision ID: c1a1e2f3g4h5
Revises: 9a9fc4631380
Create Date: 2026-03-31 01:25:39.230970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a1e2f3g4h5'
down_revision: Union[str, Sequence[str], None] = '7bf669982e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_issues_title', table_name='issues')
    op.create_index(op.f('ix_issues_title'), 'issues', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_title'), table_name='issues')
    op.create_index('ix_issues_title', 'issues', ['title'], unique=False)
    # ### end Alembic commands ###
