version = 5.4.0
archive_dir = /etc/letsencrypt/archive/doodle-choi.me
cert = /etc/letsencrypt/live/doodle-choi.me/cert.pem
privkey = /etc/letsencrypt/live/doodle-choi.me/privkey.pem
chain = /etc/letsencrypt/live/doodle-choi.me/chain.pem
fullchain = /etc/letsencrypt/live/doodle-choi.me/fullchain.pem
[renewalparams]
account = 434ef08814c6983035a05bdbab86aacf
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-03-25T17:03:58
